### ISSUE TITLE
Errors with 0.9.24 and 0.9.17

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/oobee-desktop#43]
I tried running both 0.9.24 and 0.9.17 on a M1 Max Mac and got an error both times with some basic domains.

![](https://github.com/GovTechSG/purple-hats-desktop/assets/116832/fece21d9-21a8-41e7-9f61-9f244d5f7cc6)

![](https://github.com/GovTechSG/purple-hats-desktop/assets/116832/b4489789-6584-48c2-9393-89c7b92d7c4d)

  
Having robust errors would help debut this.   
  
Thanks!

**Comment by younglim** [comment]
Hi @mgifford ,

We are aware of the issue on M1 Mac with 0.9.17, causing an error on the purple-hats backend.  Hang on for the latest release (0.9.24 is a pre-release).

I will keep you posted here once the fix is released.

**Comment by younglim** [comment]
Hi @mgifford,

Please try our pre-release (0.9.25 or later) which resolves the issue.

Thank you.

**Comment by mgifford** [comment]
Seems to be working with a later version of the code. Thanks @younglim!
