### ISSUE TITLE
Feature req: Provide a list of URLs to test from a text file

### ISSUE THREAD

**Issue by factus10** [GovTechSG/oobee-desktop#52]
I'd like to use Purple Hats desktop client to test a set of pages across time, to document improvement (or not). Being able to provide a set of pages/urls would make that magic happen.

**Comment by shaal** [comment]
👍

**Comment by shaal** [comment]
We might be able to take advantage of the "sitemap crawl" feature, but currently there is no way to customize the location of that sitemap file.

**Comment by mgifford** [comment]
Yes, even being able to put a location into the browser like file:///Users/mike/Downloads/sitemap.xml would be useful.   
  
Being able to crawl the same 100 pages every week gives you different kinds of feedback than crawling 100 pages.

**Comment by younglim** [comment]
Hi all,

We have implemented the feature to allow you to specify `file:///Users/username/sitemap.xml ` or simply the path to the file `/Users/username/sitemap.xml` `C:\Users\user\sitemap.xml`.

You may then create your own sitemap containing a list of URLs of one URL per line and save it in a simple .txt file to scan specific pages.

I hope this improvement works for your scanning use case.

**Comment by factus10** [comment]
Thank you! Yes, the use case I had in mind was to define a baseline at the beginning of a project, then test across time to see if we're improving (or not) and at the end to show the potentially positive change. Testing the same pages across the entire timeline is important to that.

**Comment by shaal** [comment]
@factus10 Thank you for adding this feature so quickly!

I found a bug, on Windows 11, when I add `file:///C:/Users/Ofer%20Shaal/Downloads/standard-sitemap.xml`, I am getting an error `Invalid sitemap.`
When I try to add this instead - `file:///C:/myfiles/standard-sitemap.xml` - it works as expected.
