### ISSUE TITLE
Sign and notarize the app package for MacOS

### ISSUE THREAD

**Issue by rpkoller** [GovTechSG/oobee-desktop#53]
Hello  my usual procedure when downloading a new app for MacOS I check if the app is build as universal binary so there is no need to install Rosetta 2 and on the other hand I check for proper code signing and notarization. with `codesign -vv -R='anchor apple generic'`  but it returns: `/Users/myuser/Downloads/Purple HATS.app: code object is not signed at all`. Would it possible to consider to add code-signing and notarization to the MacOS app package? It would add a certain level of security to the app. Best regards Ralf

**Comment by younglim** [comment]
Hi @rpkolle,

Rosetta 2 is not required to run the desktop app.  The installation of Rosetta 2 is included for the underlying scan engine.  Let me review the Rosetta 2 requirement again as we have re-engineered the scan engine over the past month - you may be on to something that it is no longer required.

On signing and notarization, I encountered errors in my attempt to notarize the app in June 2023 where the process failed after providing electron-forge packager the necessary variables.  Let me re-attempt the app notarization steps.

**Comment by mgifford** [comment]
Thanks @younglim - appreciate your responses here.

**Comment by rpkoller** [comment]
@younglim at first apologies for the late reply, your answer slipped through. and sorry i've phrased my comment too ambiguous. I've checked your app and it IS a universal binary so there is no need for installing Rosetta 2. Just outlined the two steps I always check when i download a new app for MacOS, if it is a universal binary and if it is properly signed and a universal binary it is. :) (i simply run in `file /Users/myuser/Downloads/Purple\ HATS.app/Contents/MacOS/Purple\ HATS`  when i check an app). 

and thank you for revisiting and retrying the signing and notarization!

**Comment by younglim** [comment]
Hi @rpkoller,

No worries on the universal binary part.  We have removed Rosetta2 dependency on the Purple HATS engine.

We have enabled code signing and notarisation of the app binary in the latest update 0.9.32.  You should see the benefit immediately through `codesign -vv -R='anchor apple generic' './Purple HATS.app'` with the output:
```
./Purple HATS.app: valid on disk
./Purple HATS.app: satisfies its Designated Requirement
./Purple HATS.app: explicit requirement satisfied
```

Cheers!

**Comment by rpkoller** [comment]
Awesome @younglim! Thank you so much for notarization and the signing. I've downloaded the latest release https://github.com/GovTechSG/purple-hats-desktop/releases/tag/0.9.32  and I can confirm the release is signed and notarized. yay! Thank you again and since the objective of this issue was accomplished i'll also close the issue as completed.
