### ISSUE TITLE
It should be possible to limit the scans to a single subdomain

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/oobee-desktop#55]
In scanning www.va.gov we are getting a number of subdomains from the report. It might be useful to have that information, but generally the team responsible for a subdomain only has authority for that subdomain. 

Is it possible to make sure responses are limited just to that top level domain (or for that matter any specific subdomain we choose to review)?   
  
Thanks. This tool has really come a long ways.

**Comment by greyguy21** [comment]
Hi @mgifford, 
Could you kindly provide more information about this issue you are facing and if possible, steps to reproduce it as well. 
Thank you!

**Comment by younglim** [comment]
Hi @mgifford,  

We have implemented "Allow subdomains for scans" checkbox in the latest update 0.9.32. You may uncheck it to enforce crawled pages match the same (sub-)domain as the starting URL.

**Comment by mgifford** [comment]
I apparently missed this. I'll close this for now and will re-open if needed.
