### ISSUE TITLE
Add better error messaging 

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/oobee-desktop#57]
I'm occasionally getting this:

![Screenshot after an incomplete run](https://github.com/GovTechSG/purple-hats-desktop/assets/116832/36b00a88-e9f8-4c37-88c7-dfb20be89243)

or alternatively blank screens. I tend to restart the app and it seems to run fine. Not sure if it is a caching issue or what.

**Comment by younglim** [comment]
Hi @mgifford,

This error usually means the backend engine has encountered an exception while starting or attempting a scan.

Would you be able to provide the logs when you encounter the issue?
```
cat "~/Library/Application Support/Purple HATS/Purple HATS Backend/purple-hats/errors.txt"
```

Much appreciated.

**Comment by mgifford** [comment]
Just got that error again when trying to scan www.va.gov

I got to that directory, but couldn't find a errors.txt file in the directory.

**Comment by younglim** [comment]
Hi @mgifford,

I saw the issue about two weeks ago but couldn't reproduce it.  I have just tested www.va.gov with a 5-page scan and the scan seems to progress.  

<img width="1112" alt="image" src="https://github.com/GovTechSG/purple-a11y-desktop/assets/2021525/a4533fb7-a2c5-4955-9a97-b29312005290">

Marking this is closed.  Thanks.

**Comment by mgifford** [comment]
Thanks for letting me know. Good improvements in recent releases.

**Comment by younglim** [comment]
Thank you! :)
