### ISSUE TITLE
Skip non-html pages

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/oobee-desktop#60]
Just noticed that a bunch of the errors popping up are tied to JSON files that are listed with:
  content-type: application/json

It should be easy enough to check to see that only 
  content-type: text/html;

get through.  Easy to test with something like:
  https://www.toolsvoid.com/httpheaders/

**Comment by younglim** [comment]
Hi @mgifford,  

I couldn't replicate your issue but we have implemented a check for `content-type: text/html;` in the latest update 0.9.32.

Please try it out and let me know if it resolves your issue. :)

**Comment by mgifford** [comment]
I'll close this for now and re-open it if I can replicate the problem. I haven't seen it for a while.
