### ISSUE TITLE
Must Fix vs Good to Fix vs Axe Rules vs WCAG?

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/oobee-desktop#69]
I'd just love to have some more transparency about what Must Fix and Good to Fix mean. Is it A or AA? Is it aligned with the Critical/Serious or Moderate/Minor? What are these aligned with. 

Also, I believe that Purple Hats is still using axe. If so, it is useful to highlight what version.

**Comment by younglim** [comment]
Hi @mgifford,

For details on which accessibility scan results trigger "Must Fix" / "Good to Fix" findings, you may refer to [Scan Issue Details](https://github.com/GovTechSG/purple-hats/blob/master/DETAILS.md).

I have updated the [README.md](https://github.com/GovTechSG/purple-hats-desktop/commit/27b71968de29ae7e7d67f92fccddbd06daa5cd48) for greater transparency.  Thanks.

**Comment by mgifford** [comment]
Thanks. That's great!
